// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlhbzgquypwdpacgxrpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsaGJ6Z3F1eXB3ZHBhY2d4cnB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NTE3NjEsImV4cCI6MjA1OTEyNzc2MX0.vrNyE7nVcZDPDKDJpOv9sp5QBWhfJZBLkNiFOWSqstI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);